"""
Build src/data/resources.ts from the parsed dwrolvink/titanmap data
(/tmp/objs.json). Food-spot coordinates are real in-game locations.

titanmap coordinate frame: x,y in [-84.3, +84.3], origin top-left, y down.
The map image (map.png) spans the full 168.6-unit square.

App grid: 0..4096, origin top-left, y south(down) — matches GameMap's
marker transform  [MAP_SIZE - y, x].
"""
import json, os

SPAN = 168.6
HALF = 84.3
GRID = 4096

objs = json.load(open('/tmp/objs.json'))

# icon id -> (category id, label, emoji, colour)
FOOD = {
    'acorn_img':    ('acorn',    'Acorn',    '🌰', '#c2843f'),
    'lychee_img':   ('lychee',   'Lychee',   '🍒', '#e0457b'),
    'amanita_img':  ('amanita',  'Amanita',  '🍄', '#ef4444'),
    'milkcap_img':  ('milkcap',  'Milkcap',  '🍄', '#f59e0b'),
    'tigernut_img': ('tigernut', 'Tigernut', '🥜', '#a3a31f'),
    'root_img':     ('root',     'Root',     '🥕', '#b06b3a'),
}

def to_grid(v):
    return round((v + HALF) / SPAN * GRID)

rows = []
counters = {}
for o in objs:
    icon = o.get('icon')
    if icon not in FOOD:
        continue
    x, y = o.get('x'), o.get('y')
    if x is None or y is None or x != x or y != y:  # None or NaN
        continue
    cat, label, _emoji, _col = FOOD[icon]
    gx = to_grid(x); gy = to_grid(y)
    if not (0 <= gx <= GRID and 0 <= gy <= GRID):
        continue
    counters[cat] = counters.get(cat, 0) + 1
    n = counters[cat]
    rows.append((f'{cat[:2]}-{n:03d}', cat, label, gx, gy))

header = '''// AUTO-GENERATED by scripts/build_resources.py
// Real Gondwa food-spot coordinates sourced from the community project
// dwrolvink/titanmap (GPLv3). Path of Titans © Alderon Games.
import type { Resource } from '../types';

export const resources: Resource[] = [
'''
lines = [header]
for rid, cat, label, gx, gy in rows:
    lines.append(
        f"  {{ id: '{rid}', mapId: 'gondwa', category: '{cat}', "
        f"name: '{label}', x: {gx}, y: {gy} }},\n"
    )
lines.append('];\n')

out = os.path.join(os.path.dirname(__file__), '../src/data/resources.ts')
open(out, 'w').write(''.join(lines))
print(f'wrote {len(rows)} real food markers -> {out}')
for c, n in sorted(counters.items()):
    print(f'  {n:>3}  {c}')
