"""
Robust calibration: anchor on the Great Lake centroid, scale by the
whole-island bounding box (per axis). Renders an alignment preview and,
if --write is passed, rewrites src/data/resources.ts with corrected coords.
"""
import json, collections, sys, re
import numpy as np
from PIL import Image, ImageDraw

DET = 512

def load(path, size=DET):
    return np.asarray(Image.open(path).convert('RGB').resize((size, size))).astype(int)

def lake_centroid(path, titan):
    a = load(path)
    r, g, b = a[:,:,0], a[:,:,1], a[:,:,2]
    if titan:
        m = (b > 110) & (g > 110) & (r < 160) & (b >= r) & ~((r>200)&(g>200)&(b>200))
    else:
        m = (b > r + 6) & (b > 70)
    # drop border-connected (ocean/bg)
    H, W = m.shape; seen = np.zeros_like(m, bool); dq = collections.deque()
    for x in range(W):
        for y in (0, H-1):
            if m[y,x] and not seen[y,x]: seen[y,x]=True; dq.append((y,x))
    for y in range(H):
        for x in (0, W-1):
            if m[y,x] and not seen[y,x]: seen[y,x]=True; dq.append((y,x))
    while dq:
        y,x = dq.popleft()
        for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):
            ny,nx=y+dy,x+dx
            if 0<=ny<H and 0<=nx<W and m[ny,nx] and not seen[ny,nx]: seen[ny,nx]=True; dq.append((ny,nx))
    m[seen] = False
    # largest interior blob
    seen2 = np.zeros_like(m, bool); best=None; bn=0
    for sy in range(H):
        for sx in range(W):
            if m[sy,sx] and not seen2[sy,sx]:
                dq=collections.deque([(sy,sx)]); seen2[sy,sx]=True; pts=[]
                while dq:
                    y,x=dq.popleft(); pts.append((y,x))
                    for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):
                        ny,nx=y+dy,x+dx
                        if 0<=ny<H and 0<=nx<W and m[ny,nx] and not seen2[ny,nx]: seen2[ny,nx]=True; dq.append((ny,nx))
                if len(pts)>bn: bn=len(pts); best=pts
    ys=np.array([p[0] for p in best]); xs=np.array([p[1] for p in best])
    return xs.mean()/W, ys.mean()/H

def titan_content_bbox(path):
    """titanmap content = non-white pixels (island fills the canvas?)."""
    a = load(path)
    r,g,b = a[:,:,0],a[:,:,1],a[:,:,2]
    content = ~((r>235)&(g>235)&(b>235))
    ys,xs = np.where(content)
    return xs.min()/DET, xs.max()/DET, ys.min()/DET, ys.max()/DET

def zklau_land_bbox(path):
    """zKlau land = non-ocean (greenish/brownish, not blue)."""
    a = load(path)
    r,g,b = a[:,:,0],a[:,:,1],a[:,:,2]
    land = (r > b - 4) & ((r > 70) | (g > 70))  # not strongly blue
    # ignore black padding
    land &= (r+g+b > 60)
    ys,xs = np.where(land)
    # robust bbox via percentiles to ignore stray pixels
    return (np.percentile(xs,0.5)/DET, np.percentile(xs,99.5)/DET,
            np.percentile(ys,0.5)/DET, np.percentile(ys,99.5)/DET)

tcx, tcy = lake_centroid('/tmp/titan_map.png', True)
zcx, zcy = lake_centroid('/tmp/gondwa_z4.jpg', False)
tx0,tx1,ty0,ty1 = titan_content_bbox('/tmp/titan_map.png')
zx0,zx1,zy0,zy1 = zklau_land_bbox('/tmp/gondwa_z4.jpg')
tw, th = tx1-tx0, ty1-ty0
zw, zh = zx1-zx0, zy1-zy0
sx, sy = zw/tw, zh/th
print(f'titan lake ({tcx:.3f},{tcy:.3f})  content bbox x[{tx0:.3f},{tx1:.3f}] y[{ty0:.3f},{ty1:.3f}]')
print(f'zklau lake ({zcx:.3f},{zcy:.3f})  land bbox    x[{zx0:.3f},{zx1:.3f}] y[{zy0:.3f},{zy1:.3f}]')
print(f'scale per axis: sx={sx:.3f} sy={sy:.3f}')

def transform(gx, gy):
    tnx, tny = gx/4096.0, gy/4096.0           # titan-normalised
    znx = zcx + (tnx - tcx) * sx
    zny = zcy + (tny - tcy) * sy
    return znx*4096.0, zny*4096.0

# render preview
txt = open('src/data/resources.ts').read()
pts = re.findall(r"category: '(\w+)',[^}]*x: (\d+), y: (\d+)", txt)
colors = {'acorn':(194,132,63),'lychee':(224,69,123),'amanita':(239,68,68),
          'milkcap':(245,158,11),'tigernut':(163,163,31),'root':(176,107,58)}
im = Image.open('/tmp/gondwa_z4.jpg').convert('RGB'); W,H = im.size
d = ImageDraw.Draw(im)
for cat,x,y in pts:
    zx,zy = transform(int(x), int(y))
    px,py = zx/4096*W, zy/4096*H
    c = colors.get(cat,(255,255,255)); rr=7
    d.ellipse([px-rr,py-rr,px+rr,py+rr], fill=c, outline=(255,255,255))
im.thumbnail((800,800)); im.save('/tmp/align2.jpg','JPEG',quality=85)
print('preview -> /tmp/align2.jpg')

if '--write' in sys.argv:
    cal = dict(tcx=tcx,tcy=tcy,zcx=zcx,zcy=zcy,sx=sx,sy=sy)
    json.dump(cal, open('/tmp/cal.json','w'))
    out=[]
    for cat,x,y in pts:
        zx,zy = transform(int(x), int(y))
        zx=max(0,min(4096,round(zx))); zy=max(0,min(4096,round(zy)))
        out.append((cat,zx,zy))
    # rebuild resources.ts preserving ids/labels order
    lines = ["""// AUTO-GENERATED by scripts/build_resources.py + calibrate2.py
// Real Gondwa food-spot coordinates (dwrolvink/titanmap, GPLv3) calibrated
// onto the real terrain tiles (zKlau/PathOfTitansMapsTiles).
// Path of Titans © Alderon Games.
import type { Resource } from '../types';

export const resources: Resource[] = [
"""]
    LABEL={'acorn':'Acorn','lychee':'Lychee','amanita':'Amanita','milkcap':'Milkcap','tigernut':'Tigernut','root':'Root'}
    cnt={}
    for cat,zx,zy in out:
        cnt[cat]=cnt.get(cat,0)+1
        rid=f"{cat[:2]}-{cnt[cat]:03d}"
        lines.append(f"  {{ id: '{rid}', mapId: 'gondwa', category: '{cat}', name: '{LABEL[cat]}', x: {zx}, y: {zy} }},\n")
    lines.append("];\n")
    open('src/data/resources.ts','w').write(''.join(lines))
    print(f'WROTE {len(out)} calibrated markers to resources.ts')
